name: sport_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.5.0
  firebase_core: ^2.16.0
  firebase_remote_config: ^4.2.6
  flutter_bloc: ^8.1.3
  webview_flutter: ^3.0.0
  device_info_plus: ^9.0.3
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  webview_cookie_manager: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/exercises_for_chest_images/
    - assets/images/exercises_for_back_images/
    - assets/images/leg_exercises_images/
    - assets/images/exercises_for_hands_images/
    - assets/images/shoulder_exercises_images/
    - assets/images/exercises_for_press_images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

